version: '3.7'

services:
  postgres:
    ports:
      - 5432:5432

  minio:
    ports:
      - 9000:9000

  elasticsearch:
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
