version: '3.7'

services:
  postgres:
    env_file: .env
    image: postgres
    ports:
      - 5432:5432

  minio:
    env_file: .env
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
