version: '3.7'

services:
  postgres:
    env_file: .env
    image: postgres:11
    ports:
      - 5432:5432

  minio:
    env_file: .env
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
