version: '3.7'

services:
  backend:
    build:
      context: .
      target: backend
    env_file: [.env, .env.production]

  frontend:
    build:
      context: .
      target: frontend
    env_file: [.env, .env.production]
